repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: ^charts/[^/]+/templates/

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: local
    hooks:
      - id: helm-lint
        name: lint Helm chart
        entry: helm lint charts/interview-app
        language: system
        pass_filenames: false
        files: ^charts/interview-app/
