apiVersion: v1
kind: Service
metadata:
  name: {{ include "interview-app.fullname" . }}
  labels:
    {{- include "interview-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "interview-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
